name: lintotype

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - flake8
  - ipywidgets
  - isort
  - jupyterlab >=0.35,<0.36
  - mypy
  - nodejs >=8.11,<9
  - prospector
  - pylint
  - python >=3.7,<3.8
  - tornado<6
  - yamllint
  - yapf
  - pip:
      - pyre-check
