name: lintotype

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - flake8 >=3.7.7
  - ipywidgets
  - isort
  - jupyterlab >=0.35,<0.36
  - mypy
  - mypy_extensions
  - nodejs >=8.11,<9
  - pycodestyle >=2.5.0
  - pydot
  - pygraphviz
  - pylint
  - python >=3.7,<3.8
  - tornado<6
  - yamllint
  - yapf
  - pip:
      - pyre-check
