import typing as typ

class AGraph:
    def __init__(self, dot_str: str): ...
    def draw(self, fp: typ.BinaryIO, format: str, prog: str) -> None: ...
    def nodes(self) -> typ.List[typ.Text]: ...
    def edges(self) -> typ.List[typ.Tuple[typ.Text, typ.Text]]: ...
