import typing as typ

FileContent = str

def format_str(
    src_contents: str, *, line_length: int, mode: FileMode = ...
) -> FileContent: ...

class FileMode:
    target_versions: typ.Set[int] = ...
    line_length: int = ...
    string_normalization: bool = ...
    is_pyi: bool = ...
    def get_cache_key(self) -> str: ...
